spring:
  jpa:
    show-sql: true
    hibernate:      ddl-auto: create-drop
  h2:    console:      enabled: true
   
  datasource:    url: jdbc:h2:mem:testdb
    

server:  error:    include-message: ALWAYS
    
    